---
# MCP Server Integration Role - Main Tasks
# Handles MCP server configuration with comprehensive error handling and validation

- name: Validate MCP configuration JSON syntax
  include_tasks: validate_config.yml
  when: mcp_config_file is defined

- name: Create backup of existing settings
  include_tasks: backup_settings.yml

- name: Load environment variables from .env file
  include_tasks: load_env.yml

- name: Process MCP configuration
  include_tasks: process_config.yml
  when: mcp_config_file is defined

- name: Merge MCP servers into settings
  include_tasks: merge_settings.yml

- name: Validate final configuration
  include_tasks: validate_final.yml

- name: Handle configuration errors
  include_tasks: error_handling.yml
  when: mcp_integration_error is defined

- name: Display integration summary
  debug:
    msg:
      - "MCP Integration completed successfully"
      - "Backup created: {{ settings_backup_file }}"
      - "Settings updated: {{ settings_json_path }}"
      - "MCP servers configured: {{ mcp_servers_count | default(0) }}"