task:
  id: "TASK-003"
  title: "Replace behavioral system with lean workflow executor"
  type: "enhancement"
  epic: "EPIC-SIMPLIFICATION"
  created: "$(date '+%Y-%m-%d %H:%M:%S')"
  phase: "INIT"
  
problem_description: |
  The current system has redundant behavioral enforcement (complex prompts)
  competing with the workflow system (assignment files). The workflow IS the
  behavior. We need a LEAN system where the assignment file structure drives
  all behavior, not complex behavioral patterns that can be ignored.
  
  Current bloat:
  - 9 behavioral modules with complex enforcement
  - Penalty systems and monitoring  
  - Competing with workflow structure
  
  Desired state:
  - Single workflow executor
  - Assignment file drives everything
  - No redundant enforcement