---
# Project-specific removal tasks

- name: Check if project CLAUDE.md exists
  stat:
    path: "{{ claude_project_path }}/CLAUDE.md"
  register: project_claude_md

- name: Handle project CLAUDE.md removal
  block:
    - name: Check if import line exists in project CLAUDE.md
      lineinfile:
        path: "{{ claude_project_path }}/CLAUDE.md"
        line: "@~/.claude/modes/virtual-team.md"
        state: present
      check_mode: yes
      register: project_import_exists
      
    - name: Process project CLAUDE.md with import line
      block:
        - name: Check if project backup exists
          stat:
            path: "{{ claude_project_path }}/CLAUDE.md.backup"
          register: project_backup_exists
        
        - name: Restore project CLAUDE.md from backup
          copy:
            src: "{{ claude_project_path }}/CLAUDE.md.backup"
            dest: "{{ claude_project_path }}/CLAUDE.md"
            remote_src: yes
          when: project_backup_exists.stat.exists
          register: project_backup_restored
        
        - name: Remove project backup file after restoration
          file:
            path: "{{ claude_project_path }}/CLAUDE.md.backup"
            state: absent
          ignore_errors: yes
          when: project_backup_exists.stat.exists
        
        - name: Remove virtual team integration from project CLAUDE.md (no backup case)
          block:
            - name: Read project CLAUDE.md content
              slurp:
                src: "{{ claude_project_path }}/CLAUDE.md"
              register: project_content
            
            - name: Remove import line from project
              lineinfile:
                path: "{{ claude_project_path }}/CLAUDE.md"
                line: "@~/.claude/modes/virtual-team.md"
                state: absent
            
            - name: Remove virtual team header from project
              lineinfile:
                path: "{{ claude_project_path }}/CLAUDE.md"
                line: "# Virtual Development Team"
                state: absent
            
            - name: Remove project configuration comment
              lineinfile:
                path: "{{ claude_project_path }}/CLAUDE.md"
                line: "<!-- Add your project-specific configuration below -->"
                state: absent
            
            - name: Check if project CLAUDE.md is effectively empty
              shell: |
                # Remove empty lines and whitespace-only lines, check if anything remains
                grep -v '^[[:space:]]*$' "{{ claude_project_path }}/CLAUDE.md" | wc -l
              register: project_content_lines
              changed_when: false
            
            - name: Remove empty project CLAUDE.md file
              file:
                path: "{{ claude_project_path }}/CLAUDE.md"
                state: absent
              when: project_content_lines.stdout | int == 0
              
            - name: Report project manual removal
              debug:
                msg: "Removed virtual team integration from project CLAUDE.md - {{ 'file removed (was empty)' if project_content_lines.stdout | int == 0 else 'user content preserved' }}"
          
          when: not project_backup_exists.stat.exists
        
        - name: Report project backup restoration
          debug:
            msg: "Restored project CLAUDE.md from backup - original content recovered"
          when: project_backup_exists.stat.exists
      
      when: project_import_exists.changed
    
    - name: Report no project integration found
      debug:
        msg: "No virtual team integration found in project CLAUDE.md"
      when: not project_import_exists.changed
  
  when: project_claude_md.stat.exists

- name: Report no project CLAUDE.md found
  debug:
    msg: "No project CLAUDE.md found at {{ claude_project_path }}"
  when: not project_claude_md.stat.exists