---
# Project-specific cleanup tasks

- name: Check if project CLAUDE.md exists
  stat:
    path: "{{ claude_project_path }}/CLAUDE.md"
  register: project_claude_md_exists
  when: claude_project_path != ""

- name: Remove virtual team import from project CLAUDE.md
  lineinfile:
    path: "{{ claude_project_path }}/CLAUDE.md"
    regexp: '^@~/.claude/modes/virtual-team\.md\s*$'
    state: absent
    backup: yes
  when: 
    - claude_project_path != ""
    - project_claude_md_exists.stat.exists
  register: project_claude_cleanup

- name: Remove empty lines from project CLAUDE.md after import removal
  lineinfile:
    path: "{{ claude_project_path }}/CLAUDE.md"
    regexp: '^\s*$'
    state: absent
  when: 
    - claude_project_path != ""
    - project_claude_md_exists.stat.exists
    - project_claude_cleanup.changed

- name: Check if project CLAUDE.md is now empty
  stat:
    path: "{{ claude_project_path }}/CLAUDE.md"
  register: project_claude_md_after_cleanup
  when: 
    - claude_project_path != ""
    - project_claude_cleanup.changed

- name: Read project CLAUDE.md content to check if empty
  slurp:
    src: "{{ claude_project_path }}/CLAUDE.md"
  register: project_claude_content
  when: 
    - claude_project_path != ""
    - project_claude_md_after_cleanup.stat.exists

- name: Remove empty project CLAUDE.md file
  file:
    path: "{{ claude_project_path }}/CLAUDE.md"
    state: absent
  when: 
    - claude_project_path != ""
    - project_claude_content is defined
    - (project_claude_content.content | b64decode | trim | length == 0)

- name: Display project cleanup results
  debug:
    msg:
      - "Project cleanup completed"
      - "Project path: {{ claude_project_path }}"
      - "{{ 'CLAUDE.md import removed' if project_claude_cleanup.changed else 'No project CLAUDE.md found or no changes needed' }}"
      - "{{ 'Empty CLAUDE.md file removed' if (project_claude_content is defined and (project_claude_content.content | b64decode | trim | length == 0)) else 'Project CLAUDE.md preserved' }}"
  when: claude_project_path != ""